version = 1

test_patterns = [
  "**/*.test.tsx",
  "**/*.test.ts",
  "**/*.spec.tsx",
  "**/*.spec.ts"
]

exclude_patterns = [".nx/**"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]

[[transformers]]
name = "prettier"
enabled = true

[[transformers]]
name = "standardjs"
enabled = true